### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by Zynismus16** [jw-star/91pornBot#25]
搭建后能解析地址但是无法下载上传
以下是容器日志

```
/app/pornbot.py:291: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
bot启动了!!!
消息已被删除或不存在，无法转发
 https://la3.killcovid2021.com//mp43/.mp4?st=joaNrdE3rKebrx_1Nn6LQQ&e=1686210415  
Unhandled exception on echo_all
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 54, in __call__
    result = await fn(*args, **kwargs)
TypeError: run() missing 1 required positional argument: 'viewkey'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "/app/pornbot.py", line 101, in echo_all
    await handle91(event, viewkey, viewkey_url)
  File "/app/pornbot.py", line 200, in handle91
    await  util.run(videoinfo.realM3u8, viewkey)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 92, in async_wrapped
    return await fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 51, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 354, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[]
```

**Comment by Zynismus16** [comment]
经测试该情况为pornhub链接才会出现的问题
91能解析下载视频但上传无反应，以下为日志
```
任务文件  830980142.ts  下载成功['ffmpeg -y -f concat -i "89a0a095f92d7f3fd583/89a0a095f92d7f3fd583.txt" -bsf:a aac_adtstoasc  -c copy   "89a0a095f92d7f3fd583/89a0a095f92d7f3fd583.mp4"' exited with 0]
视频合并完成
写文件及下载耗时：0:00:09
[' ffmpeg -i "89a0a095f92d7f3fd583/89a0a095f92d7f3fd583.mp4" -y -vframes 1   "89a0a095f92d7f3fd583/89a0a095f92d7f3fd583.jpg" ' exited with 0]
['ffmpeg -ss 10 -i "89a0a095f92d7f3fd583/89a0a095f92d7f3fd583.mp4" -y -c:v copy -c:a copy -avoid_negative_ts 1 -loglevel quiet  "89a0a095f92d7f3fd583/seg_89a0a095f92d7f3fd583.mp4" ' exited with 0]
```

另外该版本和 提供的Demo bot有差异
