### ISSUE TITLE
又出错了

### ISSUE THREAD

**Issue by aq859142062** [jw-star/91pornBot#9]
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "/app/pornbot.py", line 34, in <module>
    bot = TelegramClient(None, API_ID, API_HASH,
  File "/root/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 134, in start
    else self.loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 141, in _start
    await self.connect()
  File "/root/.local/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 526, in connect
    if not await self._sender.connect(self._connection(
  File "/root/.local/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 128, in connect
    await self._connect()
  File "/root/.local/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 254, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jw-star** [comment]
可能是bot被另一个程序占用了
